# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\DDE_Ocean_Sediments\Rissam\ui\plane_plorized_dock.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.dockWidget1 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget1.setObjectName("dockWidget1")
        self.dockWidgetContents1 = QtWidgets.QWidget()
        self.dockWidgetContents1.setObjectName("dockWidgetContents1")
        self.horizontalLayout1 = QtWidgets.QHBoxLayout(self.dockWidgetContents1)
        self.horizontalLayout1.setObjectName("horizontalLayout1")
        self.imageLabel1 = QtWidgets.QLabel(self.dockWidgetContents1)
        self.imageLabel1.setObjectName("imageLabel1")
        self.horizontalLayout1.addWidget(self.imageLabel1)
        self.dockWidget1.setWidget(self.dockWidgetContents1)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget1)
        self.dockWidget2 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget2.setObjectName("dockWidget2")
        self.dockWidgetContents2 = QtWidgets.QWidget()
        self.dockWidgetContents2.setObjectName("dockWidgetContents2")
        self.horizontalLayout2 = QtWidgets.QHBoxLayout(self.dockWidgetContents2)
        self.horizontalLayout2.setObjectName("horizontalLayout2")
        self.imageLabel2 = QtWidgets.QLabel(self.dockWidgetContents2)
        self.imageLabel2.setObjectName("imageLabel2")
        self.horizontalLayout2.addWidget(self.imageLabel2)
        self.dockWidget2.setWidget(self.dockWidgetContents2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget2)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        pass
